accounts/urls.py
"""Accounts URL Configuration"""

from django.urls import path, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as accounts_auth

from accounts import views
from accounts.forms import ChangePasswordForm

app_name = 'accounts'

urlpatterns = [
    path('login/', accounts_auth.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', accounts_auth.LogoutView.as_view(),  name='logout'),
    path('list/', login_required(views.ProfileList.as_view()), name='list'),
    path('create/', login_required(views.ProfileCreate.as_view()), name='create'),
    path('<int:pk>/delete/', login_required(views.ProfileDelete.as_view()), name='delete'),
    path('<int:pk>/update/', login_required(views.ProfileUpdate.as_view()), name='update'),
    path('password-change/', accounts_auth.PasswordChangeView.as_view(
      success_url=reverse_lazy('accounts:password_change_done'),
      template_name='accounts/change_password.html',
      form_class=ChangePasswordForm
    ), name='password_change'),
    path('password-change/done/', accounts_auth.PasswordChangeDoneView.as_view(
      template_name='accounts/change_password_done.html'
    ), name='password_change_done')
]

admin_taller/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from admin_taller import views

app_name = 'admin_taller'

urlpatterns = [
   path('', login_required(views.InicioTemplateView.as_view()), name='inicio'),
   # Cliente
   path('cliente/list/', login_required(views.ClienteList.as_view()), name='cliente-list'),
   path('cliente/create/', login_required(views.ClienteCreate.as_view()), name='cliente-create'),
   path('cliente/<int:pk>/delete/', login_required(views.ClienteDelete.as_view()), name='cliente-delete'),
   path('cliente/<int:pk>/update/', login_required(views.ClienteUpdate.as_view()), name='cliente-update'),
   # Vehículo
   path('vehiculo/list/', login_required(views.VehiculoList.as_view()), name='vehiculo-list'),
   path('vehiculo/create/', login_required(views.VehiculoCreate.as_view()), name='vehiculo-create'),
   path('vehiculo/<int:pk>/delete/', login_required(views.VehiculoDelete.as_view()), name='vehiculo-delete'),
   path('vehiculo/<int:pk>/update/', login_required(views.VehiculoUpdate.as_view()), name='vehiculo-update'),
   # Trabajo
   path('trabajo/list/', login_required(views.TrabajoList.as_view()), name='trabajo-list'),
   path('trabajo/create/', login_required(views.TrabajoCreate.as_view()), name='trabajo-create'),
   path('trabajo/<int:pk>/delete/', login_required(views.TrabajoDelete.as_view()), name='trabajo-delete'),
   path('trabajo/<int:pk>/update/', login_required(views.TrabajoUpdate.as_view()), name='trabajo-update'),
   # Orden de Trabajo
   path('ordentrabajo/list/', login_required(views.OrdenTrabajoList.as_view()), name='ordentrabajo-list'),
   path('ordentrabajo/create/', login_required(views.OrdenTrabajoCreate.as_view()), name='ordentrabajo-create'),
   path('ordentrabajo/<int:pk>/delete/', login_required(views.OrdenTrabajoDelete.as_view()), name='ordentrabajo-delete'),
   path('ordentrabajo/<int:pk>/update/', login_required(views.OrdenTrabajoUpdate.as_view()), name='ordentrabajo-update')
]

api/urls.py
# from django.contrib import admin
from django.urls import path
from rest_framework import routers
from django.urls.conf import include
from api import views

router = routers.DefaultRouter()
router.register('cliente', views.ClienteViewset, basename='cliente')
router.register('vehiculo', views.VehiculoViewset, basename='vehiculo')
router.register('trabajo', views.TrabajoViewset, basename='trabajo')
router.register('ordentrabajo', views.OrdenTrabajoViewset, basename='ordentrabajo')

urlpatterns = [
    path('', include(router.urls)),
    path('clientes/', views.cliente_list),
    path('clientes/<int:pk>', views.cliente_detail),
    path('vehiculos/', views.vehiculo_list),
    path('vehiculos/<int:pk>', views.vehiculo_detail),
    path('trabajos/', views.trabajo_list),
    path('trabajos/<int:pk>', views.trabajo_detail),
    path('ordenestrabajo/', views.ordentrabajo_list),
    path('ordenestrabajo/<int:pk>', views.ordentrabajo_detail),
    
]

taller/urls.py
"""taller URL Configuration"""

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('admin_taller.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django.forms import ModelForm
from django.forms import CharField, ModelMultipleChoiceField
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.utils.translation import gettext_lazy
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate

from accounts.models import Profile, UserAccount
from django.contrib.auth.models import Group, Permission
from django import forms
# from authy.api import AuthyApiClient
from django.conf import settings

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(
       widget=forms.PasswordInput,
       help_text=gettext_lazy("Ingresa tu contraseña"),
       label=gettext_lazy('Contraseña'),
    )
    def __init__(self, usuario, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        ## add attributes
        for name, field in self.fields.items():
            field.widget.attrs['placeholder'] = field.help_text
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = get_user_model()
        custom_fields = ('first_name', 'middle_name', 'last_name', 'email', 'groups' )
        fields = UserCreationForm.Meta.fields + custom_fields

    def save(self, *args, **kwargs):
        super(RegisterForm, self).save(*args, **kwargs)
        self.instance.groups.set(self.cleaned_data.get('groups'))
        self.instance.save()
        return self.instance

class ProfileForm(ModelForm):
    # fields of UserAccounts
    first_name = CharField(
       label=gettext_lazy('Nombre'), help_text=gettext_lazy("Ingrese su nombre"))
    middle_name = CharField(label=gettext_lazy('Apellido Paterno'), help_text=gettext_lazy("Ingrese su apellido"))
    last_name = CharField(label=gettext_lazy('Apellido Materno'), help_text=gettext_lazy("Ingrese su apellido"))
    email = CharField(label=gettext_lazy('Correo'),)
    username = CharField(label=gettext_lazy('Nombre de usuario') )

    def __init__(self, usuario, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].initial = self.instance.user.first_name
        self.fields['middle_name'].initial = self.instance.user.middle_name
        self.fields['last_name'].initial = self.instance.user.last_name
        self.fields['email'].initial = self.instance.user.email
        self.fields['username'].initial = self.instance.user.username
        self.usuario = usuario

        ## add attributes
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['email'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['style'] = 'background-color: #e3e6ec;'
            self.fields['username'].widget.attrs['readonly'] = True
            self.fields['username'].widget.attrs['style'] = 'background-color: #e3e6ec;'

        # check this - redundant
        for name, field in self.fields.items():
            field.widget.attrs['placeholder'] = field.help_text
            field.widget.attrs['class'] = 'form-control'

    def save(self, *args, **kwargs):
        super(ProfileForm, self).save(*args, **kwargs)
        self.instance.user.first_name = self.cleaned_data.get('first_name')
        self.instance.user.middle_name = self.cleaned_data.get('middle_name')
        self.instance.user.last_name = self.cleaned_data.get('last_name')
        self.instance.user.save()
        return self.instance

    class Meta:
        model = Profile
        custom_fields = (
           'picture',
           'first_name',
           'middle_name',
           'last_name',
           'email',
           'username',
           'office_phone',
           'mobile_phone',
            'street_address',
            'zipcode_address',
            'city_address',
            'state_address',
            'country_address'
         )
        fields = custom_fields

class PermissionForm(ModelForm):
    # fields of UserAccounts
    user_permissions = ModelMultipleChoiceField(
        required = False,
        queryset = Permission.objects.filter(name__contains = "Access"),
        widget = forms.CheckboxSelectMultiple(),
        label = gettext_lazy('User permissions'),
    )

    def __init__(self, *args, **kwargs):
        super(PermissionForm, self).__init__(*args, **kwargs)
        if self.instance.user.user_permissions.all():
           self.fields['user_permissions'].initial = self.instance.user.user_permissions.all()
        else:
           permisos_grupo = [permiso.replace('admin_unit.', '') for permiso in self.instance.user.get_group_permissions()]
           self.fields['user_permissions'].initial = Permission.objects.filter(codename__in=permisos_grupo)

        self.fields['user_permissions'].label_from_instance = lambda obj: "%s" % _(obj.name)

        # check this - redundant
        for name, field in self.fields.items():
            field.widget.attrs['placeholder'] = field.help_text

    def save(self, *args, **kwargs):
        super(PermissionForm, self).save(*args, **kwargs)
        self.instance.user.user_permissions.set(self.cleaned_data.get('user_permissions'))
        self.instance.user.save()
        return self.instance

    class Meta:
        model = Profile
        custom_fields = ('user_permissions',)
        fields = custom_fields

class ChangePasswordForm(PasswordChangeForm):
   def __init__(self, *args, **kwargs):
      super(ChangePasswordForm, self).__init__(*args, **kwargs)
      for visible in self.visible_fields():
         visible.field.widget.attrs['class'] = 'form-control string'

accounts/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.http import HttpResponse, HttpResponseRedirect

import json
from django.db.models import Q
from django.core import serializers
from django.core.paginator import Paginator
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.translation import gettext_lazy

from accounts.models import Profile, UserAccount, Profile
from accounts.forms import RegisterForm, ProfileForm, PermissionForm

import os
from django.conf import settings
from django.contrib.auth.models import Permission, User
from django.contrib.contenttypes.models import ContentType

class RegisterView(CreateView):
   model = UserAccount
   form_class = RegisterForm
   template_name = 'accounts/register.html'
   success_message = gettext_lazy("Usuario registrado correctamente")

   def post(self, request, *args, **kwargs):
      form = self.form_class(request.POST)
      if form.is_valid():
         new_user = form.save()
         #because changed username for email in authentication
         username = form.cleaned_data.get('email')
         password = form.cleaned_data.get('password1')
         user = authenticate(username = username, password = password)
         if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse_lazy('viewer:dashboard'))
         else:
            return render(request, self.template_name, {'form': form})

### User Profile ###
class ProfileList(ListView):
   model = Profile
   success_message = '{} {} {}'.format(
      gettext_lazy('Lista de'), 
      gettext_lazy('Usuarios'),
      gettext_lazy('Obtenida')
   )

   def post(self, request, *args, **kwargs):
      if request.is_ajax():
         page_start = request.POST['start']
         page_len = request.POST['length']
         draw = request.POST['draw']
         recordsTotal = 0
         recordsFiltered = 0
         page = int(int(page_start)/int(page_len)) + 1
         word_search = request.POST['search[value]']
         order_by = '-id'
         if request.POST['order[0][column]'] == '1':
            order_by = 'id'
         if request.POST['order[0][column]'] == '2':
            order_by = 'user__first_name'
         if request.POST['order[0][column]'] == '3':
            order_by = 'user__middle_name'
         if request.POST['order[0][column]'] == '4':
            order_by = 'user__last_name'
         if request.POST['order[0][column]'] == '5':
            order_by = 'user__email'
         if request.POST['order[0][column]'] == '6':
            order_by = 'mobile_phone__contains'
         if request.POST['order[0][dir]'] == 'desc':
            order_by = '-' + order_by

         recordsTotal = Profile.objects.all().filter().count()
         users = Profile.objects.all().filter(
            Q(user__first_name__contains = word_search) |
            Q(user__last_name__contains = word_search) |
            Q(user__email__contains = word_search) |
            Q(mobile_phone__contains = word_search)
         ).order_by(order_by)
         paginator = Paginator(users, int(page_len))
         page_users = paginator.page(page).object_list
         data = serializers.serialize('json', page_users, use_natural_foreign_keys=True, )
         dato = json.dumps({
            "draw": draw,
            "recordsTotal": recordsTotal,
            "recordsFiltered": paginator.count,
            "data": json.loads(data)
         })

         return HttpResponse(dato, content_type='application/json')

class ProfileCreate(CreateView):
   model = Profile
   form_class = RegisterForm
   success_message = "{} {}".format(gettext_lazy("Usuario"), gettext_lazy("Creado con Éxito"))

   def get_context_data(self, **kwargs):
      context = super(ProfileCreate, self).get_context_data(**kwargs)
      context["grupos"] = self.request.user.groups.all()
      return context

   def get_success_url(self, **kwargs):
      context = super().get_context_data(**kwargs)
      user = context['object']
      messages.success(self.request, self.success_message)
      return reverse_lazy('accounts:update',  kwargs = {'pk': user.id})

   def get_form_kwargs(self, **kwargs):
      form_kwargs = super(ProfileCreate, self).get_form_kwargs(**kwargs)
      form_kwargs["usuario"] = self.request.user
      return form_kwargs

class ProfileUpdate(UpdateView):
   model = Profile
   form_class = ProfileForm
   success_message = "{} {}".format(gettext_lazy("Usario"), gettext_lazy("Actualizado Exitosamente"))

   def get_context_data(self, **kwargs):
      context = super(ProfileUpdate, self).get_context_data(**kwargs)
      context["grupos"] = self.request.user.groups.all()
      return context

   def get_success_url(self, **kwargs):
      context = super().get_context_data(**kwargs)
      user = context['object']
      messages.success(self.request, self.success_message)
      return reverse_lazy('accounts:update',  kwargs = {'pk': user.id})

   def get_form_kwargs(self, **kwargs):
      form_kwargs = super(ProfileUpdate, self).get_form_kwargs(**kwargs)
      form_kwargs["usuario"] = self.request.user
      return form_kwargs

   def form_valid(self, form):
      if ((self.object.pk == self.request.user.id) or
         (self.request.user.is_superuser) or
         ( 'ADMIN' in [ g.name for g in self.request.user.groups.all()] )
      ):
         self.object = form.save()
         return super().form_valid(form)
      else:
         return super().form_invalid(form)

class ProfileDelete(DeleteView):
   model = Profile
   success_message = "{} {}".format(gettext_lazy("Usuario"), gettext_lazy("Eliminado Exitosamente"))

   #for request delete via ajax
   def post(self, request, *args, **kwargs):
      if request.is_ajax():
         self.object = self.get_object()
         self.object.delete()
         dato = json.dumps({
            "message": "{} {}".format(gettext_lazy("Usuario"), gettext_lazy("Eliminado Exitosamente"))
         })
         return HttpResponse(dato, content_type="application/json")

accounts/templates/accounts/cambio_contrasenas_admin.html
{% extends "admin_taller/index.html" %}
{% load i18n static %}

{% block cssfiles %} {% endblock %}

{% block breadcrumb %}
<div class="kt-subheader__breadcrumbs">
    
    <a href="{% url 'accounts:list' %}" class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--home">{% trans 'Users' %}</a>
    <span class="kt-subheader__breadcrumbs-separator"></span>
        
    {% if object %}
        <a href="{% url 'accounts:update' user.profile.id %}" class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--home">{% trans "Profile" %}</a>
        <span class="kt-subheader__breadcrumbs-separator"></span>
    {% endif %}
    <a href="" class="kt-subheader__breadcrumbs-link ">{% trans "Restablecer contraseña" %} {{ usuario }}</a>
</div>
{% endblock %}

{% block content %}
<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
                Restablecer contraseña: {{usuario}}
            </h3>
        </div>
    </div>
    <form action="{% url 'accounts:fn-cambio-contrasena-admin' %}" method="POST" id="form-change-password">
        {% csrf_token %}

        <div class="kt-portlet__body">
            <input type="hidden" name="pk" value="{{pk}}">
            <div class="row">
                <div class="col-6">
                    <label for="">Nueva contraseña:</label>
                    <input type="password" class="form-control" placeholder="Ingrese una nueva contraseña" name="password" id="password" >
                </div>
                <div class="col-6">
                    <label for="">Confirmar contraseña:</label>
                    <input type="password" class="form-control" placeholder="Confirme nueva contraseña" name="password2" id="password2" >
                </div>
            </div>
        </div>
        <div class="kt-portlet__foot text-right">
            <a class="btn btn-secondary" href="{% url 'accounts:list' %}">
                {% trans "Regresar" %}
            </a>
            <button type="submit" class="btn btn-success">
                {% trans "Save" %}
            </button>
        </div>
    </form>
</div>
{% endblock %}

{% block jsfiles %}
<script src="{% static 'base/assets/js/base.js' %}" type="text/javascript"></script>
<script>
    $( document ).ready(function() {
        var pass1 = "";
        var pass2 = "";
        // $(  ).submit(function( event ) {
        $("#form-change-password").on('submit', function(e){
            pass1 = $("#password").val();
            pass2 = $("#password2").val();
            var patron = new RegExp("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[ -/:-@\[-`{-~]).{6,64}$");

            if(pass1 != pass2){
                event.preventDefault();
                toastr.warning("<b>Asegúrese que las contraseñas sean iguales.</b>", "{% trans 'Las contraseñas no coinciden.' %}");
            }
            else if (!patron.test(pass1) ){
                event.preventDefault();
                toastr.warning("<b>La contraseña debe tener Mayúsculas, minúsculas, un carácter especial y números.</b>", "{% trans 'Contraseña inválida' %}");
            }
        });   
    });
</script>
{% endblock %}

accounts/templates/accounts/change_password_done.html
{% extends "admin_taller/index.html" %}
{% load i18n static %}

{% block cssfiles %} {% endblock %}

{% block breadcrumb %}
   <div class="kt-subheader  kt-grid__item" id="kt_subheader">
      <div class="kt-container kt-container--fluid ">
         <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">{% trans "Cuenta" %}</h3>
            <span class="kt-subheader__separator kt-hidden"></span>
            <div class="kt-subheader__breadcrumbs">
               <span class="kt-subheader__breadcrumbs-separator"></span>
               <a href="{% url 'accounts:password_change' %}" class="kt-subheader__breadcrumbs-link">
                  {% trans "Cambio de contraseña" %}
               </a>
            </div>
         </div>
      </div>
   </div>
{% endblock %}

{% block contenido %}
   <div class="kt-portlet kt-portlet--mobile">
      <div class="kt-portlet__head">
         <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
               {% trans "Cambio de contraseña exitoso" %}
            </h3>
         </div>
      </div>
      <div class="kt-portlet__body">
         <h5>{% trans "Su contraseña fue cambiada." %}</h5>
      </div>
   </div>
{% endblock %}

{% block jsfiles %}
   <script>
      $(document).ready(function () {
         setTimeout(function () {
            window.location.href = "{% url 'admin_taller:inicio' %}";
         }, 3000);
      });
   </script>
{% endblock %}

accounts/templates/accounts/profile_list.html
{% extends "admin_taller/index.html" %}
{% load i18n static %}

{% block cssfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'base/datatables/css/jquery.dataTables.min.css' %}" />
{% endblock %}

{% block breadcrumb %}
<div class="kt-subheader__breadcrumbs">
    <a href="" class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--home">{% trans 'Usuarios' %}</a>
</div>
{% endblock %}

{% block content %}
<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">
                {% trans 'Lista de' %} {% trans 'Usuarios' %}
            </h3>
        </div>

        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-toolbar">
                <div class="dropdown dropdown-inline">
                    <button type="button" class="btn btn-clean" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="las la-cog"></i>
                        <span class="d-none d-md-inline-flex">{% trans 'Acciones' %}</span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <ul class="kt-nav">
                            {% if grupos_nivel1 %}
                                <li class="kt-nav__item">
                                    <a href="{% url 'accounts:create' %}" class="kt-nav__link">
                                        <i class="las la-plus"></i>
                                        <span class="kt-nav__link-text">{% trans 'Nuevo' %}</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">
        <table id="table-viewer-list" class="table table-hover">
            <thead>
                <tr>
                    <th>{% trans 'Aciones' %}</th>
                    <th>ID</th>
                    <th>{% trans 'Nombre' %}</th>
                    <th>{% trans 'Apellido' %}</th>
                    <th>{% trans 'Nombre de usuario' %}</th>
                    <th>{% trans 'Teléfono móvil' %}</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block jsfiles %}
<script type="text/javascript" src="{% static 'base/datatables/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'base/assets/js/base.js' %}" type="text/javascript"></script>
<script>
    // -----------------------------------------------------------------
    $.fn.dataTable.render.ellipsis = function (cutoff) {
        return function (data, type, row) {
            if (data) {
                return type === 'display' && data.length > cutoff ?
                    //data.substr( 0, (cutoff/2) ) +'... ...' + data.substr(data.length - (cutoff/2)) : data;
                    data.substr(0, cutoff) + '...' : data;
            }
            else return '';
        }
    };
    {% get_current_language as LANGUAGE_CODE %}
    var table_viewer_list = $('#table-viewer-list').DataTable({
        "scrollX": true,
        "scrollY": "350px",
        "scrollCollapse": true,
        "language": {
            "url": {% if LANGUAGE_CODE == "en" %} "//cdn.datatables.net/plug-ins/1.10.19/i18n/English.json" {% else %} "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json" {% endif %},
        },
        "responsive": true,
        "oSearch": { "sSearch": '{{word_search}}' },
        "processing": true,
        "serverSide": true,
        "deferRender": true,
        "order": [[ 1, "asc" ]],
        "ajax": {
                "url": "{% url 'accounts:list' %}",
                "type": "post",
                "data": function(d) { d.csrfmiddlewaretoken = '{{csrf_token}}'; },
                "dataSrc": "data"
        },
        "columns": [
            {
                    "data": null, "orderable": false, "searchable": false,
                    "render": function (data) {
                        return '<div class="btn-toolbar" role="toolbar" aria-label="Toolbar">' +
                                    '<div class="btn-group mr-2" role="group" aria-label="Buttons">' +
                                        {% if grupos_nivel1 %}
                                            '<button onclick="javascript:viewer_recovery_password('+data.pk+');" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="{% trans "Reestablecer" %}"><i class="las la-redo-alt"></i></button>'
                                            +
                                        {% endif %}
                                        {% if grupos_nivel1 %}
                                            '<button onclick="javascript:viewer_update('+data.pk+');" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="{% trans "Editar" %}"><i class="las la-edit"></i></button>'
                                            +
                                        {% endif %}
                                        {% if grupos_nivel2 %}
                                        {% endif %}
                                        
                                    '</div>' +
                                '</div>';
                    },
                    "className": 'dt-head-center dt-body-right',
                },
                { "data": "pk", "orderable": true, "searchable": true, },
                { "data": "fields.user.first_name", "orderable": true, "searchable": true, },
                { "data": "fields.user.last_name", "orderable": true, "searchable": true, },
                { "data": "fields.user.email", "orderable": true, "searchable": true, },
                { "data": "fields.mobile_phone", "orderable": true, "searchable": true, },
        ]
    });

    $('#table-viewer-list tbody').on('click', 'tr', function () {
        if ($(this).hasClass('selected')) {
            $(this).removeClass('selected');
        }
        else {
            table_viewer_list.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
        }
    });

    function viewer_update(id) {
        location.href = "/accounts/"+id+"/update/";
    }
    function viewer_permissions(id) {
        location.href = "/accounts/"+id+"/permissions-change/";
    }
    function viewer_recovery_password(id) {
        location.href = "/accounts/"+id+"/recovery-password/";
    }

    $(document).ready(function () {
        {% if messages %}
            {% for message in messages %}
                toastr.info("{{ message }}", "{% trans 'Mensaje' %}");
            {% endfor %}
        {% endif %}
    });
</script>
{% endblock %}

accounts/templates/accounts/useraccount_form.html
{% extends "admin_taller/index.html" %}
{% load i18n static %}

{% block cssfiles %} {% endblock %}

{% block breadcrumb %}
<div class="kt-subheader__breadcrumbs">
   <a href="{% url 'accounts:list' %}" class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--home">{% trans 'Usuarios' %}</a>
   <span class="kt-subheader__breadcrumbs-separator"></span>
   <a href="#" class="kt-subheader__breadcrumbs-link">{% trans 'Cambiar permisos' %}</a>
</div>
{% endblock %}

{% block content %}
<div class="kt-portlet kt-portlet--mobile">
   <div class="kt-portlet__head">
      <div class="kt-portlet__head-label">
         <h3 class="kt-portlet__head-title">
            {% trans 'Cambiar permisos' %}
         </h3>
      </div>
   </div>
   <form enctype="multipart/form-data" method="post">
      <div class="kt-portlet__body wrap-permisos">
         {% csrf_token %}
         {{ form }}
         <div class="form-group form-actions">

         </div>
      </div>
      <div class="kt-portlet__foot text-right">
         <a class="btn btn-secondary" href="{% url 'accounts:list' %}">
            {% trans 'Atrás' %}
         </a>
         <button type="submit" class="btn btn-success">
            {% trans 'Guardar' %}
         </button>
      </div>
   </form>
</div>
{% endblock %}

{% block jsfiles %}
<script src="{% static 'base/assets/js/base.js' %}" type="text/javascript"></script>
<script>
   $( document ).ready(function() {
      {% if messages %}
         {% for message in messages %}
            toastr.success("<b>{{ message }}</b>", "{% trans 'Mensaje' %}");
         {% endfor %}
      {% endif %}
   });
</script>
{% endblock %}