admin_taller/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from admin_taller import views

app_name = 'admin_taller'

urlpatterns = [
   path('', login_required(views.InicioTemplateView.as_view()), name='inicio'),
   # Cliente
   path('cliente/list/', login_required(views.ClienteList.as_view()), name='cliente-list'),
   path('cliente/create/', login_required(views.ClienteCreate.as_view()), name='cliente-create'),
   path('cliente/<int:pk>/delete/', login_required(views.ClienteDelete.as_view()), name='cliente-delete'),
   path('cliente/<int:pk>/update/', login_required(views.ClienteUpdate.as_view()), name='cliente-update'),
   # Vehículo
   path('vehiculo/list/', login_required(views.VehiculoList.as_view()), name='vehiculo-list'),
   path('vehiculo/create/', login_required(views.VehiculoCreate.as_view()), name='vehiculo-create'),
   path('vehiculo/<int:pk>/delete/', login_required(views.VehiculoDelete.as_view()), name='vehiculo-delete'),
   path('vehiculo/<int:pk>/update/', login_required(views.VehiculoUpdate.as_view()), name='vehiculo-update'),
   # Trabajo
   path('trabajo/list/', login_required(views.TrabajoList.as_view()), name='trabajo-list'),
   path('trabajo/create/', login_required(views.TrabajoCreate.as_view()), name='trabajo-create'),
   path('trabajo/<int:pk>/delete/', login_required(views.TrabajoDelete.as_view()), name='trabajo-delete'),
   path('trabajo/<int:pk>/update/', login_required(views.TrabajoUpdate.as_view()), name='trabajo-update'),
   # Orden de Trabajo
   path('ordentrabajo/list/', login_required(views.OrdenTrabajoList.as_view()), name='ordentrabajo-list'),
   path('ordentrabajo/create/', login_required(views.OrdenTrabajoCreate.as_view()), name='ordentrabajo-create'),
   path('ordentrabajo/<int:pk>/delete/', login_required(views.OrdenTrabajoDelete.as_view()), name='ordentrabajo-delete'),
   path('ordentrabajo/<int:pk>/update/', login_required(views.OrdenTrabajoUpdate.as_view()), name='ordentrabajo-update')
]

api/urls.py
# from django.contrib import admin
from django.urls import path
from rest_framework import routers
from django.urls.conf import include
from api import views

router = routers.DefaultRouter()
router.register('cliente', views.ClienteViewset, basename='cliente')
router.register('vehiculo', views.VehiculoViewset, basename='vehiculo')
router.register('trabajo', views.TrabajoViewset, basename='trabajo')
router.register('ordentrabajo', views.OrdenTrabajoViewset, basename='ordentrabajo')

urlpatterns = [
    path('', include(router.urls)),
    path('clientes/', views.cliente_list),
    path('clientes/<int:pk>', views.cliente_detail),
    path('vehiculos/', views.vehiculo_list),
    path('vehiculos/<int:pk>', views.vehiculo_detail),
    path('trabajos/', views.trabajo_list),
    path('trabajos/<int:pk>', views.trabajo_detail),
    path('ordenestrabajo/', views.ordentrabajo_list),
    path('ordenestrabajo/<int:pk>', views.ordentrabajo_detail),
    
]

taller/urls.py
"""taller URL Configuration"""

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('admin_taller.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_taller/models.py
from django.db import models

# Create your models here.

admin_taller/forms.py
from django.forms import ModelForm
from django import forms
from api.models import Cliente, Vehiculo, Trabajo, OrdenTrabajo

class DateInput(forms.DateInput):
   input_type = "date"

class ClienteForm(ModelForm):
   def __init__(self, *args, **kwargs):
      super(ClienteForm, self).__init__(*args, **kwargs)
      # Add attributes
      for name, field in self.fields.items():
         field.widget.attrs["placeholder"] = field.help_text
         field.widget.attrs["class"] = "form-control"
   
   class Meta:
      model = Cliente
      fields = "__all__"

class VehiculoForm(ModelForm):
   def __init__(self, *args, **kwargs):
      super(VehiculoForm, self).__init__(*args, **kwargs)
      # Add attributes
      for name, field in self.fields.items():
         field.widget.attrs["placeholder"] = field.help_text
         field.widget.attrs["class"] = "form-control"
         if name == "descripcion":
            field.widget.attrs["rows"] = "2"
   
   class Meta:
      model = Vehiculo
      fields = "__all__"

class TrabajoForm(ModelForm):
   def __init__(self, *args, **kwargs):
      super(TrabajoForm, self).__init__(*args, **kwargs)
      # Add attributes
      for name, field in self.fields.items():
         field.widget.attrs["placeholder"] = field.help_text
         field.widget.attrs["class"] = "form-control"
         if name == "descripcion":
            field.widget.attrs["rows"] = "2"
   
   class Meta:
      model = Trabajo
      fields = "__all__"

class OrdenTrabajoForm(ModelForm):
   def __init__(self, *args, **kwargs):
      super(OrdenTrabajoForm, self).__init__(*args, **kwargs)
      # Add attributes
      for name, field in self.fields.items():
         field.widget.attrs["placeholder"] = field.help_text
         field.widget.attrs["class"] = "form-control"
   
   class Meta:
      model = OrdenTrabajo
      fields = "__all__"

admin_taller/views.py
import json
from django.db.models import Q
from django.shortcuts import render
from django.core import serializers
from django.contrib import messages
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.views.generic.list import ListView
from django.utils.translation import gettext_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

# Models
from api.models import Cliente, Vehiculo, Trabajo, OrdenTrabajo

from admin_taller.forms import ClienteForm, VehiculoForm, TrabajoForm, OrdenTrabajoForm

import logging
from logging.config import fileConfig

# Get an instance of a logger
fileConfig("logging_config.ini")
logger = logging.getLogger(__name__)

# Create your views here.
class InicioTemplateView(TemplateView):
   template_name = 'admin_taller/index.html'

class ClienteList(ListView):
   template_name = 'admin_taller/cliente_list.html'
   model = Cliente
   success_message = "{} {} {}".format(
      gettext_lazy("Lista de "),
      gettext_lazy("Cliente"),
      gettext_lazy("Obtenida")
   )

   def post(self, request, *args, **kwargs):
      if request.is_ajax():
         page_start = request.POST["start"]
         page_len = request.POST["length"]
         draw = request.POST["draw"]
         recordsTotal = 0
         recordsFiltered = 0
         page = int(int(page_start) / int(page_len)) + 1
         columna = request.POST['order[0][column]']
         nombre_columna = request.POST['columns[{}][data]'.format(columna)]
         word_search = request.POST["search[value]"]
         order_by = "id"
         if nombre_columna == "id":
            order_by = "id"
         if nombre_columna == "nombre":
            order_by = "nombre"
         if nombre_columna == "apellido":
            order_by = "apellido"
         if nombre_columna == "telefono":
            order_by = "telefono"
         if nombre_columna == "rfc":
            order_by = "rfc"
         if request.POST["order[0][dir]"] == "desc":
            order_by = "-" + order_by
         recordsTotal = Cliente.objects.all().filter().count()
         cliente = Cliente.objects.all().filter(
            Q(nombre__contains = word_search) |
            Q(apellido__contains = word_search) |
            Q(telefono__contains = word_search) |
            Q(rfc__contains = word_search)
         ).order_by(order_by)
         paginator = Paginator(cliente, int(page_len))
         page_cliente = paginator.page(page).object_list
         data = serializers.serialize(
            "json",
            page_cliente,
            use_natural_foreign_keys=True,
         )
         dato = json.dumps({
            "draw": draw,
            "recordsTotal": recordsTotal,
            "recordsFiltered": paginator.count,
            "data": json.loads(data),
         })
         logger.info('{} {}'.format(self.success_message + ' por', self.request.user))
         return HttpResponse(dato, content_type="application/json")

class ClienteCreate(CreateView):
   template_name = 'admin_taller/cliente_form.html'
   model = Cliente
   form_class = ClienteForm
   success_message = "{} {}".format(
      gettext_lazy("Cliente • "),
      gettext_lazy("Creado exitosamente")
   )
   # success_message = "Save"

   def get_success_url(self, **kwargs):
      context = super().get_context_data(**kwargs)
      dato = context["object"]
      messages.success(self.request, self.success_message)
      logger.info('{} {}'.format(self.success_message + " con el ID: " + str(dato.id) + ' por', self.request.user))
      return reverse_lazy("admin_taller:cliente-list")

class ClienteUpdate(UpdateView):
   template_name = 'admin_taller/cliente_form.html'
   model = Cliente
   form_class = ClienteForm
   success_message = "{} {}".format(
      gettext_lazy("Cliente • "),
      gettext_lazy("Actualizado exitosamente")
   )

   def get_success_url(self, **kwargs):
      context = super().get_context_data(**kwargs)
      dato = context["object"]
      messages.success(self.request, self.success_message)
      logger.info('{} {}'.format(self.success_message + " con el ID: " + str(dato.id) + ' por', self.request.user))
      return reverse_lazy("admin_taller:cliente-list")

class ClienteDelete(DeleteView):
   model = Cliente
   success_message = "{} {}".format(
      gettext_lazy("Cliente • "),
      gettext_lazy("Eliminado exitosamente")
   )

   # for request delete via ajax
   def post(self, request, *args, **kwargs):
      try:
         if request.is_ajax():
            self.object = self.get_object()
            objeto_id = self.object.id
            self.object.delete()
            dato = json.dumps({
               "message": "{} {}".format(
                  gettext_lazy("Cliente • "),
                  gettext_lazy("Eliminado exitosamente")
               )
            })
            logger.info('{} {}'.format(self.success_message + " con el ID: " + str(objeto_id) + ' por', self.request.user))
            return HttpResponse(dato, content_type="application/json")
      except Exception as e:
         if e.__class__.__name__ == "ProtectedError":
            dato = json.dumps({
               "message": "No se puede eliminar, debido a que el cliente tiene beneficiarios asignados."
            })
            return HttpResponse(dato, content_type="application/json")

class VehiculoList(ListView):
   template_name = 'admin_taller/vehiculo_list.html'
   model = Vehiculo
   success_message = "{} {} {}".format(
      gettext_lazy("Lista de "),
      gettext_lazy("Vehiculo"),
      gettext_lazy("Obtenida")
   )

   def post(self, request, *args, **kwargs):
      if request.is_ajax():
         page_start = request.POST["start"]
         page_len = request.POST["length"]
         draw = request.POST["draw"]
         recordsTotal = 0
         recordsFiltered = 0
         page = int(int(page_start) / int(page_len)) + 1
         columna = request.POST['order[0][column]']
         nombre_columna = request.POST['columns[{}][data]'.format(columna)]
         word_search = request.POST["search[value]"]
         order_by = "id"
         if nombre_columna == "id":
            order_by = "id"
         if nombre_columna == "cliente":
            order_by = "cliente"
         if nombre_columna == "tipo":
            order_by = "tipo"
         if nombre_columna == "nombre":
            order_by = "nombre"
         if nombre_columna == "descripcion":
            order_by = "descripcion"
         if nombre_columna == "placa":
            order_by = "placa"
         if nombre_columna == "marca":
            order_by = "marca"
         if nombre_columna == "modelo":
            order_by = "modelo"
         if nombre_columna == "anio":
            order_by = "anio"
         if request.POST["order[0][dir]"] == "desc":
            order_by = "-" + order_by
         recordsTotal = Vehiculo.objects.all().filter().count()
         vehiculo = Vehiculo.objects.all().filter(
            Q(cliente__nombre__contains = word_search) |
            Q(tipo__contains = word_search) |
            Q(nombre__contains = word_search) |
            Q(descripcion__contains = word_search) |
            Q(placa__contains = word_search) |
            Q(marca__contains = word_search) |
            Q(modelo__contains = word_search) |
            Q(anio__contains = word_search)
         ).order_by(order_by)
         paginator = Paginator(vehiculo, int(page_len))
         page_vehiculo = paginator.page(page).object_list
         data = serializers.serialize(
            "json",
            page_vehiculo,
            use_natural_foreign_keys=True,
         )
         dato = json.dumps({
            "draw": draw,
            "recordsTotal": recordsTotal,
            "recordsFiltered": paginator.count,
            "data": json.loads(data),
         })
         logger.info('{} {}'.format(self.success_message + ' por', self.request.user))
         return HttpResponse(dato, content_type="application/json")

class VehiculoCreate(CreateView):
   template_name = 'admin_taller/vehiculo_form.html'
   model = Vehiculo
   form_class = VehiculoForm
   success_message = "{} {}".format(
      gettext_lazy("Vehiculo • "),
      gettext_lazy("Creado exitosamente")
   )
   # success_message = "Save"

   def get_success_url(self, **kwargs):
      context = super().get_context_data(**kwargs)
      dato = context["object"]
      messages.success(self.request, self.success_message)
      logger.info('{} {}'.format(self.success_message + " con el ID: " + str(dato.id) + ' por', self.request.user))
      return reverse_lazy("admin_taller:vehiculo-list")

class VehiculoUpdate(UpdateView):
   template_name = 'admin_taller/vehiculo_form.html'
   model = Vehiculo
   form_class = VehiculoForm
   success_message = "{} {}".format(
      gettext_lazy("Vehiculo • "),
      gettext_lazy("Actualizado exitosamente")
   )

   def get_success_url(self, **kwargs):
      context = super().get_context_data(**kwargs)
      dato = context["object"]
      messages.success(self.request, self.success_message)
      logger.info('{} {}'.format(self.success_message + " con el ID: " + str(dato.id) + ' por', self.request.user))
      return reverse_lazy("admin_taller:vehiculo-list")

class VehiculoDelete(DeleteView):
   model = Vehiculo
   success_message = "{} {}".format(
      gettext_lazy("Vehiculo • "),
      gettext_lazy("Eliminado exitosamente")
   )

   # for request delete via ajax
   def post(self, request, *args, **kwargs):
      try:
         if request.is_ajax():
            self.object = self.get_object()
            objeto_id = self.object.id
            self.object.delete()
            dato = json.dumps({
               "message": "{} {}".format(
                  gettext_lazy("Vehiculo • "),
                  gettext_lazy("Eliminado exitosamente")
               )
            })

admin_taller/templates/admin_taller/ordentrabajo_list.html
{% extends "admin_taller/index.html" %}
{% load i18n static %}

{% block cssfiles %}
   <link rel="stylesheet" type="text/css" href="{% static 'admin_taller/datatables/css/datatables.bundle.css' %}" />
{% endblock %}

{% block breadcrumb %}
<div class="kt-grid__item m-2 p-2" id="kt_subheader">
   <div class="kt-container kt-container--fluid ">
      <div class="kt-subheader__main">
         <div class="kt-subheader__breadcrumbs">
            <a href="{% url 'admin_taller:inicio' %}" class="kt-subheader__breadcrumbs-link">
               <li class="fas fa-home"></li>
               {% trans "INICIO" %}
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="{% url 'admin_taller:ordentrabajo-list' %}" class="kt-subheader__breadcrumbs-link">
               {% trans "ORDEN DE TRABAJO" %}
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a class="kt-subheader__breadcrumbs-link">
               {% trans "LISTADO" %}
            </a>
         </div>
      </div>
   </div>
</div>
{% endblock %}

{% block contenido %}
<div class="kt-portlet kt-portlet--mobile">
   <div class="kt-portlet__head">
      <div class="kt-portlet__head-label">
         <h3 class="kt-portlet__head-title">
            {% trans "Listado de Órdenes de Trabajo" %}
         </h3>
      </div>
      <div class="kt-portlet__head-toolbar">
         <a href="{% url 'admin_taller:ordentrabajo-create' %}" class="btn btn-brand">
            <i class="fas fa-plus mr-3"></i>
            {% trans "Agregar" %}
         </a>
      </div>
   </div>
   <div class="kt-portlet__body">
      <table id="table-list" class="table table-striped- table-hover responsive no-wrap"></table>
   </div>
</div>
{% endblock %}

{% block jsfiles %}
<script type="text/javascript" src="{% static 'admin_taller/datatables/js/datatables.bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'admin_taller/js/sweet-alert.min.js' %}"></script>

<script>
   $(".menu_servicio").addClass("active");
   
   $(document).ready(function () {
      {%if messages %}
         {%for message in messages %}
            toastr.success("{{ message }}", "{% trans 'Mensaje' %}");
         {% endfor %}
      {% endif %}
   });

   var table_list = $("#table-list").DataTable({
      "select": true,
      "language": {
         "url": idioma
      },
      "responsive": true,
      "bFilter": true,
      "oSearch": {
         "sSearch": "{{word_search}}"
      },
      "processing": true,
      "serverSide": true,
      "deferRender": true,
      "order": [
         [1, "asc"]
      ],
      "ajax": {
         "url": "{% url 'admin_taller:ordentrabajo-list' %}",
         "type": "post",
         "data": function (d) {
            d.csrfmiddlewaretoken = "{{csrf_token}}";
         },
         "dataSrc": "data"
      },
      "columns": [
         {
            "data": null,
            "title": "{% trans 'Opciones' %}",
            "orderable": false,
            "orderable": false,
            "searchable": false,
            "render": function (data) {
               return '<div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Toolbar">' +
                  '<div class="btn-group mr-2" role="group" aria-label="Buttons">' +
                  '<button onclick="javascript:registro_update(' + data.pk +
                  ');" class="btn btn-sm btn-secondary btn-icon btn-icon-md" title="{% trans "Editar" %}"><i class="fas fa-edit"></i></button>' +
                  '<button onclick="javascript:registro_delete(' + data.pk +
                  ');" class="btn btn-sm btn-secondary btn-icon btn-icon-md" title="{% trans "Eliminar" %}"><i class="fas fa-trash"></i></button>' +
                  '</div>' +
                  '</div>';
            },
            "class": "text-center",
         },
         {
            "data": "fields.cliente",
            "title": "{% trans 'Cliente' %}",
            "orderable": true,
            "searchable": true,
         },
         {
            "data": "fields.vehiculo",
            "title": "{% trans 'vehiculo' %}",
            "orderable": true,
            "searchable": true,
         },
         {
            "data": "fields.numero",
            "title": "{% trans 'Número' %}",
            "orderable": true,
            "searchable": true,
         },
         {
            "data": "fields.estado",
            "title": "{% trans 'Estado' %}",
            "orderable": true,
            "searchable": true
         },
         {
            "data": "fields.trabajo",
            "title": "{% trans 'Trabajo' %}",
            "orderable": true,
            "searchable": true
         },
         {
            "data": "fields.total",
            "title": "{% trans 'Total' %}",
            "orderable": true,
            "searchable": true,
            class: "text-right",
            render: $.fn.dataTable.render.number(",", ".", 2, "$")
         }
      ],
   });

   function registro_delete(id) {
      swal({
         title: "{% trans '¿Está seguro de borrar el registro?' %}",
         text: "{% trans '¡Una vez eliminado no se podrá recuperar!' %}",
         icon: "warning",
         buttons: ["{% trans 'No' %}", "{% trans 'Sí' %}"],
         dangerMode: true,
      })
      .then((eliminar) => {
         if (eliminar) {
            $.ajax({
            method: "post",
            url: "/ordentrabajo/" + id + "/delete/",
            data: {
               csrfmiddlewaretoken: "{{csrf_token}}"
            },
            }).done(function (msg) {
               toastr.success(msg.message, "{% trans 'Mensaje' %}");
               table_list.row(".selected").remove().draw(false);
            })
            .fail(function () {
               toastr.error("{% trans 'Error eliminando registro.' %}", "{% trans 'Mensaje' %}");
            })
         }
      });
   }

   function registro_update(id) {
      location.href = "/ordentrabajo/" + id + "/update/";
   }
</script>
{% endblock %}

admin_taller/templates/admin_taller/trabajo_list.html
{% extends "admin_taller/index.html" %}
{% load i18n static %}

{% block cssfiles %}
   <link rel="stylesheet" type="text/css" href="{% static 'admin_taller/datatables/css/datatables.bundle.css' %}" />
{% endblock %}

{% block breadcrumb %}
<div class="kt-grid__item m-2 p-2" id="kt_subheader">
   <div class="kt-container kt-container--fluid ">
      <div class="kt-subheader__main">
         <div class="kt-subheader__breadcrumbs">
            <a href="{% url 'admin_taller:inicio' %}" class="kt-subheader__breadcrumbs-link">
               <li class="fas fa-home"></li>
               {% trans "INICIO" %}
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="{% url 'admin_taller:trabajo-list' %}" class="kt-subheader__breadcrumbs-link">
               {% trans "TRABAJO" %}
            </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a class="kt-subheader__breadcrumbs-link">
               {% trans "LISTADO" %}
            </a>
         </div>
      </div>
   </div>
</div>
{% endblock %}

{% block contenido %}
<div class="kt-portlet kt-portlet--mobile">
   <div class="kt-portlet__head">
      <div class="kt-portlet__head-label">
         <h3 class="kt-portlet__head-title">
            {% trans "Listado de Trabajos" %}
         </h3>
      </div>
      <div class="kt-portlet__head-toolbar">
         <a href="{% url 'admin_taller:trabajo-create' %}" class="btn btn-brand">
            <i class="fas fa-plus mr-3"></i>
            {% trans "Agregar" %}
         </a>
      </div>
   </div>
   <div class="kt-portlet__body">
      <table id="table-list" class="table table-striped- table-hover responsive no-wrap"></table>
   </div>
</div>
{% endblock %}

{% block jsfiles %}
<script type="text/javascript" src="{% static 'admin_taller/datatables/js/datatables.bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'admin_taller/js/sweet-alert.min.js' %}"></script>

<script>
   $(".menu_servicio").addClass("active");
   
   $(document).ready(function () {
      {%if messages %}
         {%for message in messages %}
            toastr.success("{{ message }}", "{% trans 'Mensaje' %}");
         {% endfor %}
      {% endif %}
   });

   var table_list = $("#table-list").DataTable({
      "select": true,
      "language": {
         "url": idioma
      },
      "responsive": true,
      "bFilter": true,
      "oSearch": {
         "sSearch": "{{word_search}}"
      },
      "processing": true,
      "serverSide": true,
      "deferRender": true,
      "order": [
         [1, "asc"]
      ],
      "ajax": {
         "url": "{% url 'admin_taller:trabajo-list' %}",
         "type": "post",
         "data": function (d) {
            d.csrfmiddlewaretoken = "{{csrf_token}}";
         },
         "dataSrc": "data"
      },
      "columns": [
         {
            "data": null,
            "title": "{% trans 'Opciones' %}",
            "orderable": false,
            "orderable": false,
            "searchable": false,
            "render": function (data) {
               return '<div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Toolbar">' +
                  '<div class="btn-group mr-2" role="group" aria-label="Buttons">' +
                  '<button onclick="javascript:registro_update(' + data.pk +
                  ');" class="btn btn-sm btn-secondary btn-icon btn-icon-md" title="{% trans "Editar" %}"><i class="fas fa-edit"></i></button>' +
                  '<button onclick="javascript:registro_delete(' + data.pk +
                  ');" class="btn btn-sm btn-secondary btn-icon btn-icon-md" title="{% trans "Eliminar" %}"><i class="fas fa-trash"></i></button>' +
                  '</div>' +
                  '</div>';
            },
            "class": "text-center",
         },
         {
            "data": "fields.nombre",
            "title": "{% trans 'Nombre' %}",
            "orderable": true,
            "searchable": true,
         },
         {
            "data": "fields.descripcion",
            "title": "{% trans 'Descripcion' %}",
            "orderable": true,
            "searchable": true,
         },
         {
            "data": "fields.cantidad",
            "title": "{% trans 'Cantidad' %}",
            "orderable": true,
            "searchable": true,
         },
         {
            "data": "fields.precio",
            "title": "{% trans 'Precio' %}",
            "orderable": true,
            "searchable": true,
            class: "text-right",
            render: $.fn.dataTable.render.number(",", ".", 2, "$")
         }
      ],
   });

   function registro_delete(id) {
      swal({
         title: "{% trans '¿Está seguro de borrar el registro?' %}",
         text: "{% trans '¡Una vez eliminado no se podrá recuperar!' %}",
         icon: "warning",
         buttons: ["{% trans 'No' %}", "{% trans 'Sí' %}"],
         dangerMode: true,
      })
      .then((eliminar) => {
         if (eliminar) {
            $.ajax({
            method: "post",
            url: "/trabajo/" + id + "/delete/",
            data: {
               csrfmiddlewaretoken: "{{csrf_token}}"
            },
            }).done(function (msg) {
               toastr.success(msg.message, "{% trans 'Mensaje' %}");
               table_list.row(".selected").remove().draw(false);
            })
            .fail(function () {
               toastr.error("{% trans 'Error eliminando registro.' %}", "{% trans 'Mensaje' %}");
            })
         }
      });
   }

   function registro_update(id) {
      location.href = "/trabajo/" + id + "/update/";
   }
</script>
{% endblock %}